# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'
post_install do |installer|
    # 需要指定编译版本的第三方的名称
    myTargets = ['Translucid']
    
    installer.pods_project.targets.each do |target|
        if myTargets.include? target.name
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '4.0'
            end
        end
    end
end

use_frameworks!

target 'WhatsGod' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'RealmSwift'
  
  pod 'LYEmptyView'
  
  pod 'SnapKit', '~> 4.0.0'
  # Pods for WhatsGod
  
  pod 'FWPopupView'

  pod 'Hue'

#  pod 'NVActivityIndicatorView' 
  pod 'CryptoSwift'
  
  pod 'ComplimentaryGradientView'

#  pod 'Translucid', '~> 0.0.2'
  
  pod 'DKImagePickerController'
  
   pod 'IBAnimatable'
   
   pod 'Chrysan'
   
   pod 'IQKeyboardManagerSwift'
   
   pod 'SSZipArchive'

end
